version: "3"
services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    container_name:
      myrediscont

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    links:
      - redis