version: "3"
services:

  logstash-client:
    image: docker.elastic.co/logstash/logstash:${ES_TAG}
    container_name: logstash-client
    depends_on:
      - redis
    volumes:
      - ./client/config:/config
      - ./client/logs:/logs
    environment:
      - JAVACMD=/usr/bin/java
      - LS_SETTINGS_DIR=/config
      - SERVICE_NAME=logstash
      - SERVICE_DESCRIPTION=logstash
    entrypoint:
      - /usr/share/logstash/bin/logstash

  redis:
    image: redis
    expose:
      - 6379
    container_name:
      myrediscont

  logstash-ingest:
    image: docker.elastic.co/logstash/logstash:${ES_TAG}
    container_name: logstash-ingest
    depends_on:
      - redis
    volumes:
      - ./ingest/config:/config
    environment:
      - JAVACMD=/usr/bin/java
      - LS_SETTINGS_DIR=/config
      - SERVICE_NAME=logstash
      - SERVICE_DESCRIPTION=logstash
    entrypoint:
      - /usr/share/logstash/bin/logstash

  elasticsearch-ingest-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}
    container_name: elasticsearch-ingest-1
    expose:
      - 9200
      - 9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.name=elasticsearch
      - "discovery.zen.ping.unicast.hosts=elasticsearch-ingest-2"
      - node.master=true
      - node.ingest=true
      - node.data=false

  elasticsearch-ingest-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}
    container_name: elasticsearch-ingest-2
    expose:
      - 9200
      - 9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.name=elasticsearch
      - "discovery.zen.ping.unicast.hosts=elasticsearch-ingest-1"
      - node.master=false
      - node.ingest=true
      - node.data=false

  elasticsearch-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}
    expose:
      - 9200
      - 9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.name=elasticsearch
      - "discovery.zen.ping.unicast.hosts=elasticsearch-ingest-1,elasticsearch-ingest-2"
      - node.master=false
      - node.ingest=false
      - node.data=true

  elasticsearch-query:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}
    expose:
      - 9200
      - 9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.name=elasticsearch
      - "discovery.zen.ping.unicast.hosts=elasticsearch-ingest-1,elasticsearch-ingest-2"
      - node.master=false
      - node.ingest=false
      - node.data=false

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_TAG}
    container_name: kibana
    depends_on:
      - redis
      - logstash-client
      - logstash-ingest
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch-query:9200"
